import { createState, m12 } from "./__tests__/helpers";
import { buildDRE } from "./dre";
import { buildCashFlow, buildRecebivelMensal } from "./cashflow";
import { resolveEffectiveRegime } from "./regime";
import { deriveBalancoFechamento } from "./balancoFechamento";
import { deriveAbertura } from "./aberturaDerivada";

const st = createState({ revenue: { bruta: m12(50_000), pmr: 0, pmp: 0 } });
const regime = resolveEffectiveRegime(st);
const { dre } = buildDRE(st, regime);
const cf = buildCashFlow(st);
const res = deriveBalancoFechamento({ state: st, dre, cf });
const ab = deriveAbertura({ state: st, impostosMensais: dre.impostosTotal });
const sum = (a?:number[]) => (a??[]).reduce((x,y)=>x+(y||0),0);

console.log("ativo", res.totals.ativo);
console.log("passivo", res.totals.passivo);
console.log("pl", res.totals.pl);
console.log("dif", res.totals.diferenca);
console.log("caixa fim", cf.saldoFinal[11]);
console.log("recebivel anual", sum(buildRecebivelMensal(st,dre)));
console.log("recebimentos DFC", sum(cf.recebimentos));
console.log("CPV anual", sum(dre.cpv));
console.log("pagFornec DFC", sum(cf.pagamentosFornecedores));
console.log("impostos total", sum(dre.impostosTotal));
console.log("pagImpostos DFC", sum(cf.pagamentosImpostos));
console.log("lucroLiquido", sum(dre.lucroLiquido));
console.log("aportes", sum(cf.aportes));
console.log("dividendos", sum(cf.dividendos));
console.log("capex", sum(cf.capex));
console.log("financeiros DFC", sum(cf.pagamentosFinanceiros));
console.log("fixos", sum(cf.pagamentosFixos));
console.log("variaveis", sum(cf.pagamentosVariaveis));
console.log("recFin", sum(cf.receitasFinanceiras));
console.log("empCap", sum(cf.emprestimosCaptados));
console.log("amort", sum(cf.amortizacoes));
console.log("abertura CR", ab.contasReceber.value, "forn", ab.fornecedores.value, "impPagar", ab.impostosPagar.value, "sal", ab.salariosEncargos.value);
console.log("balanco ativoCirc", JSON.stringify(res.balanco.ativoCirculante));
console.log("balanco passivoCirc", JSON.stringify(res.balanco.passivoCirculante));
console.log("balanco pl", JSON.stringify(res.balanco.patrimonioLiquido));
