/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CheckoutSucessoRouteImport } from './routes/checkout.sucesso'
import { Route as SharedShareIdRouteImport } from './routes/shared.$shareId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPublicHooksReconcileCheckoutIntentsRouteImport } from './routes/api/public/hooks/reconcile-checkout-intents'
import { Route as ApiPublicHooksTrialCleanupRouteImport } from './routes/api/public/hooks/trial-cleanup'
import { Route as ApiPublicHooksWebhookRetryRouteImport } from './routes/api/public/hooks/webhook-retry'
import { Route as ApiPublicPaymentsCheckoutRouteImport } from './routes/api/public/payments/checkout'
import { Route as ApiPublicPaymentsIntentStatusRouteImport } from './routes/api/public/payments/intent-status'
import { Route as ApiPublicPaymentsResendMagicLinkRouteImport } from './routes/api/public/payments/resend-magic-link'
import { Route as ApiPublicTrialActivateRouteImport } from './routes/api/public/trial/activate'
import { Route as ApiPublicTrialRequestRouteImport } from './routes/api/public/trial/request'
import { Route as ApiPublicPaymentsWebhookAsaasRouteImport } from './routes/api/public/payments/webhook.asaas'
import { Route as ApiPublicPaymentsWebhookStripeRouteImport } from './routes/api/public/payments/webhook.stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSucessoRoute = CheckoutSucessoRouteImport.update({
  id: '/checkout/sucesso',
  path: '/checkout/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedShareIdRoute = SharedShareIdRouteImport.update({
  id: '/shared/$shareId',
  path: '/shared/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksReconcileCheckoutIntentsRoute =
  ApiPublicHooksReconcileCheckoutIntentsRouteImport.update({
    id: '/api/public/hooks/reconcile-checkout-intents',
    path: '/api/public/hooks/reconcile-checkout-intents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTrialCleanupRoute =
  ApiPublicHooksTrialCleanupRouteImport.update({
    id: '/api/public/hooks/trial-cleanup',
    path: '/api/public/hooks/trial-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWebhookRetryRoute =
  ApiPublicHooksWebhookRetryRouteImport.update({
    id: '/api/public/hooks/webhook-retry',
    path: '/api/public/hooks/webhook-retry',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsCheckoutRoute =
  ApiPublicPaymentsCheckoutRouteImport.update({
    id: '/api/public/payments/checkout',
    path: '/api/public/payments/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsIntentStatusRoute =
  ApiPublicPaymentsIntentStatusRouteImport.update({
    id: '/api/public/payments/intent-status',
    path: '/api/public/payments/intent-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsResendMagicLinkRoute =
  ApiPublicPaymentsResendMagicLinkRouteImport.update({
    id: '/api/public/payments/resend-magic-link',
    path: '/api/public/payments/resend-magic-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrialActivateRoute = ApiPublicTrialActivateRouteImport.update({
  id: '/api/public/trial/activate',
  path: '/api/public/trial/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrialRequestRoute = ApiPublicTrialRequestRouteImport.update({
  id: '/api/public/trial/request',
  path: '/api/public/trial/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookAsaasRoute =
  ApiPublicPaymentsWebhookAsaasRouteImport.update({
    id: '/api/public/payments/webhook/asaas',
    path: '/api/public/payments/webhook/asaas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookStripeRoute =
  ApiPublicPaymentsWebhookStripeRouteImport.update({
    id: '/api/public/payments/webhook/stripe',
    path: '/api/public/payments/webhook/stripe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/shared/$shareId': typeof SharedShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/hooks/reconcile-checkout-intents': typeof ApiPublicHooksReconcileCheckoutIntentsRoute
  '/api/public/hooks/trial-cleanup': typeof ApiPublicHooksTrialCleanupRoute
  '/api/public/hooks/webhook-retry': typeof ApiPublicHooksWebhookRetryRoute
  '/api/public/payments/checkout': typeof ApiPublicPaymentsCheckoutRoute
  '/api/public/payments/intent-status': typeof ApiPublicPaymentsIntentStatusRoute
  '/api/public/payments/resend-magic-link': typeof ApiPublicPaymentsResendMagicLinkRoute
  '/api/public/trial/activate': typeof ApiPublicTrialActivateRoute
  '/api/public/trial/request': typeof ApiPublicTrialRequestRoute
  '/api/public/payments/webhook/asaas': typeof ApiPublicPaymentsWebhookAsaasRoute
  '/api/public/payments/webhook/stripe': typeof ApiPublicPaymentsWebhookStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/shared/$shareId': typeof SharedShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/hooks/reconcile-checkout-intents': typeof ApiPublicHooksReconcileCheckoutIntentsRoute
  '/api/public/hooks/trial-cleanup': typeof ApiPublicHooksTrialCleanupRoute
  '/api/public/hooks/webhook-retry': typeof ApiPublicHooksWebhookRetryRoute
  '/api/public/payments/checkout': typeof ApiPublicPaymentsCheckoutRoute
  '/api/public/payments/intent-status': typeof ApiPublicPaymentsIntentStatusRoute
  '/api/public/payments/resend-magic-link': typeof ApiPublicPaymentsResendMagicLinkRoute
  '/api/public/trial/activate': typeof ApiPublicTrialActivateRoute
  '/api/public/trial/request': typeof ApiPublicTrialRequestRoute
  '/api/public/payments/webhook/asaas': typeof ApiPublicPaymentsWebhookAsaasRoute
  '/api/public/payments/webhook/stripe': typeof ApiPublicPaymentsWebhookStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/checkout/sucesso': typeof CheckoutSucessoRoute
  '/shared/$shareId': typeof SharedShareIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/hooks/reconcile-checkout-intents': typeof ApiPublicHooksReconcileCheckoutIntentsRoute
  '/api/public/hooks/trial-cleanup': typeof ApiPublicHooksTrialCleanupRoute
  '/api/public/hooks/webhook-retry': typeof ApiPublicHooksWebhookRetryRoute
  '/api/public/payments/checkout': typeof ApiPublicPaymentsCheckoutRoute
  '/api/public/payments/intent-status': typeof ApiPublicPaymentsIntentStatusRoute
  '/api/public/payments/resend-magic-link': typeof ApiPublicPaymentsResendMagicLinkRoute
  '/api/public/trial/activate': typeof ApiPublicTrialActivateRoute
  '/api/public/trial/request': typeof ApiPublicTrialRequestRoute
  '/api/public/payments/webhook/asaas': typeof ApiPublicPaymentsWebhookAsaasRoute
  '/api/public/payments/webhook/stripe': typeof ApiPublicPaymentsWebhookStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/api/feedback'
    | '/api/health'
    | '/auth/callback'
    | '/checkout/sucesso'
    | '/shared/$shareId'
    | '/api/auth/$'
    | '/api/public/hooks/reconcile-checkout-intents'
    | '/api/public/hooks/trial-cleanup'
    | '/api/public/hooks/webhook-retry'
    | '/api/public/payments/checkout'
    | '/api/public/payments/intent-status'
    | '/api/public/payments/resend-magic-link'
    | '/api/public/trial/activate'
    | '/api/public/trial/request'
    | '/api/public/payments/webhook/asaas'
    | '/api/public/payments/webhook/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/api/feedback'
    | '/api/health'
    | '/auth/callback'
    | '/checkout/sucesso'
    | '/shared/$shareId'
    | '/api/auth/$'
    | '/api/public/hooks/reconcile-checkout-intents'
    | '/api/public/hooks/trial-cleanup'
    | '/api/public/hooks/webhook-retry'
    | '/api/public/payments/checkout'
    | '/api/public/payments/intent-status'
    | '/api/public/payments/resend-magic-link'
    | '/api/public/trial/activate'
    | '/api/public/trial/request'
    | '/api/public/payments/webhook/asaas'
    | '/api/public/payments/webhook/stripe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/landing'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/api/feedback'
    | '/api/health'
    | '/auth/callback'
    | '/checkout/sucesso'
    | '/shared/$shareId'
    | '/api/auth/$'
    | '/api/public/hooks/reconcile-checkout-intents'
    | '/api/public/hooks/trial-cleanup'
    | '/api/public/hooks/webhook-retry'
    | '/api/public/payments/checkout'
    | '/api/public/payments/intent-status'
    | '/api/public/payments/resend-magic-link'
    | '/api/public/trial/activate'
    | '/api/public/trial/request'
    | '/api/public/payments/webhook/asaas'
    | '/api/public/payments/webhook/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiHealthRoute: typeof ApiHealthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CheckoutSucessoRoute: typeof CheckoutSucessoRoute
  SharedShareIdRoute: typeof SharedShareIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicHooksReconcileCheckoutIntentsRoute: typeof ApiPublicHooksReconcileCheckoutIntentsRoute
  ApiPublicHooksTrialCleanupRoute: typeof ApiPublicHooksTrialCleanupRoute
  ApiPublicHooksWebhookRetryRoute: typeof ApiPublicHooksWebhookRetryRoute
  ApiPublicPaymentsCheckoutRoute: typeof ApiPublicPaymentsCheckoutRoute
  ApiPublicPaymentsIntentStatusRoute: typeof ApiPublicPaymentsIntentStatusRoute
  ApiPublicPaymentsResendMagicLinkRoute: typeof ApiPublicPaymentsResendMagicLinkRoute
  ApiPublicTrialActivateRoute: typeof ApiPublicTrialActivateRoute
  ApiPublicTrialRequestRoute: typeof ApiPublicTrialRequestRoute
  ApiPublicPaymentsWebhookAsaasRoute: typeof ApiPublicPaymentsWebhookAsaasRoute
  ApiPublicPaymentsWebhookStripeRoute: typeof ApiPublicPaymentsWebhookStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/sucesso': {
      id: '/checkout/sucesso'
      path: '/checkout/sucesso'
      fullPath: '/checkout/sucesso'
      preLoaderRoute: typeof CheckoutSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$shareId': {
      id: '/shared/$shareId'
      path: '/shared/$shareId'
      fullPath: '/shared/$shareId'
      preLoaderRoute: typeof SharedShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reconcile-checkout-intents': {
      id: '/api/public/hooks/reconcile-checkout-intents'
      path: '/api/public/hooks/reconcile-checkout-intents'
      fullPath: '/api/public/hooks/reconcile-checkout-intents'
      preLoaderRoute: typeof ApiPublicHooksReconcileCheckoutIntentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trial-cleanup': {
      id: '/api/public/hooks/trial-cleanup'
      path: '/api/public/hooks/trial-cleanup'
      fullPath: '/api/public/hooks/trial-cleanup'
      preLoaderRoute: typeof ApiPublicHooksTrialCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/webhook-retry': {
      id: '/api/public/hooks/webhook-retry'
      path: '/api/public/hooks/webhook-retry'
      fullPath: '/api/public/hooks/webhook-retry'
      preLoaderRoute: typeof ApiPublicHooksWebhookRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/checkout': {
      id: '/api/public/payments/checkout'
      path: '/api/public/payments/checkout'
      fullPath: '/api/public/payments/checkout'
      preLoaderRoute: typeof ApiPublicPaymentsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/intent-status': {
      id: '/api/public/payments/intent-status'
      path: '/api/public/payments/intent-status'
      fullPath: '/api/public/payments/intent-status'
      preLoaderRoute: typeof ApiPublicPaymentsIntentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/resend-magic-link': {
      id: '/api/public/payments/resend-magic-link'
      path: '/api/public/payments/resend-magic-link'
      fullPath: '/api/public/payments/resend-magic-link'
      preLoaderRoute: typeof ApiPublicPaymentsResendMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trial/activate': {
      id: '/api/public/trial/activate'
      path: '/api/public/trial/activate'
      fullPath: '/api/public/trial/activate'
      preLoaderRoute: typeof ApiPublicTrialActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trial/request': {
      id: '/api/public/trial/request'
      path: '/api/public/trial/request'
      fullPath: '/api/public/trial/request'
      preLoaderRoute: typeof ApiPublicTrialRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook/asaas': {
      id: '/api/public/payments/webhook/asaas'
      path: '/api/public/payments/webhook/asaas'
      fullPath: '/api/public/payments/webhook/asaas'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookAsaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook/stripe': {
      id: '/api/public/payments/webhook/stripe'
      path: '/api/public/payments/webhook/stripe'
      fullPath: '/api/public/payments/webhook/stripe'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiHealthRoute: ApiHealthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CheckoutSucessoRoute: CheckoutSucessoRoute,
  SharedShareIdRoute: SharedShareIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicHooksReconcileCheckoutIntentsRoute:
    ApiPublicHooksReconcileCheckoutIntentsRoute,
  ApiPublicHooksTrialCleanupRoute: ApiPublicHooksTrialCleanupRoute,
  ApiPublicHooksWebhookRetryRoute: ApiPublicHooksWebhookRetryRoute,
  ApiPublicPaymentsCheckoutRoute: ApiPublicPaymentsCheckoutRoute,
  ApiPublicPaymentsIntentStatusRoute: ApiPublicPaymentsIntentStatusRoute,
  ApiPublicPaymentsResendMagicLinkRoute: ApiPublicPaymentsResendMagicLinkRoute,
  ApiPublicTrialActivateRoute: ApiPublicTrialActivateRoute,
  ApiPublicTrialRequestRoute: ApiPublicTrialRequestRoute,
  ApiPublicPaymentsWebhookAsaasRoute: ApiPublicPaymentsWebhookAsaasRoute,
  ApiPublicPaymentsWebhookStripeRoute: ApiPublicPaymentsWebhookStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
